### ISSUE TITLE
NixOS binary cache?

### ISSUE THREAD

**Issue by Galagora** [shajra/nix-haskell-hls#1]
Hey, this repo is really great. Would you mind adding NixOS to the CI, since this works much better than the Nixpkgs version?

**Comment by shajra** [comment]
Hi @galagora.  Not sure I fully understand your request.  Did you try setting up the shajra.cachix.org cache?  Because I believe the Linux build should cover NixOS.  Unless you're getting a cache miss.  In which case, I can investigate further.  Cachix does have an eviction policy that I may eventually bump up against.

I know the docs on this repo are incomplete.  I plan on working on that this weekend.  But I did lay down some docs that I just use as a template for all my Nix-based repositories.  Here's the section where I discuss how to set up shajra.cachix.org:
https://github.com/shajra/nix-hls/blob/master/doc/nix.md#sec-3-2

After that, I'll be curious if you then get prebuilt binaries for NixOS (I run NixOS myself, so I feel this should work).

**Comment by Galagora** [comment]
I did initially get a cache miss, but I think that was caused by some local changes I forgot about. My current binary has the is the same as the one in your cache (`/nix/store/zdyxw428nxrfy49l6yqmk69v4qpdkw1g-haskell-language-server-ghc8102`).
