### ISSUE TITLE
Overriding the pinned versions of sources

### ISSUE THREAD

**Issue by jmickelin** [shajra/nix-haskell-hls#4]
Hi!

I'm trying to set up a derivation to make this available in our developer shells using `fetchFromGitHub` on this repo. Our monorepo already has its own pinned version of the IOHK `haskell.nix` as well as `nixpkgs`, which leads to our `shell.nix` derivation unnecessarily pulling in two versions of both of these. Furthermore, our configuration turns out a bit clunky since we are specifying things like `nixpkgs-pin` in multiple locations¹.

Is there a recommended way to "bring your own" copies of `haskell.nix` and `nixpkgs`? I'm used to seeing arguments like `{ pkgs ? <nixpkgs> }:` to packages, but your setup seems different. I understand you are using Niv for package management, which might be the reason it's done this way. Should I put together my own `sources` and feed it in as an argument?

¹ Of course, this last problem can be solved with some refactoring of our Nix files to supply the `nixpkgs-pin` as argument to our `haskell.nix` setup, but I'm still interested to know if there is a more idiomatic way to do it.

**Comment by shajra** [comment]
Hi,

So I really eschew any usage of the angle-bracket syntax in Nix (e.g. `<nixpkgs>`).  The reason is that it opens us up to environment variables messing with our derivation, and we lose a hold on determinism.  Incidentally, this is one benefit of Nix Flakes, but I just haven't moved to using Flakes yet.

You noted that you are pulling down down different versions of Nixpkgs and Haskell.nix.  This isn't intrinsically bad.  If you pull another version of Haskell.nix, you will certainly get a cache miss from my Cachix repository.  On top of that, messing around with dependencies breaks the confidence from any testing I do in my CI via GitHub Actions.

You may also notice that downloading multiple versions of a thing happens quite a lot in Nix.  For instance, you may be tickled to see how many downloads of `coreutils` you have sitting around in `/nix/store`, even after a Nix garbage collection.  So in a way, downloading the exact version of a dependency linked to by a third-party is a pretty idiomatic Nix way to do things.

That said, you're right that I'm using Niv, a precursor to Flakes, and I did kind of set it up to be a parameter passed into some Nix expressions.  Given the discussion above, I wouldn't recommend you mess with that, but you're free to do what works for you.  The likely outcome will be a cache miss.

I'm also very inconsistent with how I parameterize these things across all my projects.  I think what I might do is come up with a better personal standard.  But I don't have that just yet.  You're right that you can call the expression by supplying your own sources attribute set.  You can even load mine first, and then put your overloads on top of it.  That's not too difficult to do.  I'm not sure if I'm inclined to do that overloading within my projects or not.  I'll leave this issue open as a reminder to think about it eventually.

**Comment by shajra** [comment]
Hi @jmickelin,

So I've gone through my Nix-based repositories and come up with a convention, and one that's rolled into the main branch of this one one as well.  The top-level `default.nix` file is my strong guidance to users of what configuration I have established as a public contract for users to play around with.  In the case of Nix dependencies, this way people get the exact versions of things that I have tested with.

So in this project's case, the parameters of the top-level `default.nix` file and the corresponding `config.nix` file are actually spartan, just `ghcVersion` and `hlsUnstable`.

But for the advanced tinkerer who accepts what they are signing up for (perhaps less empathy from me when dependencies I never tested against don't work), I've made the internal `nix/default.nix` more flexible.  Currently it has the following parameters:
- `externalOverrides`
- `ghcVersion`
- `hlsUnstable`
- `checkMaterialization`
- `nixpkgs-pin`
- `index-state`
- `index-sha256`

For the purposes of this issue, the `externalOverrides` should meet your need.  It allows you to override only the external dependencies you want to coming from Niv's `sources.json` file.  Everything else will be pinned as usual.

I believe this gets you what you wanted, and it's a pattern I can use across all my Nix-based projects.  And I can still avoid pulling anything from environment variables, which is really just step backwards in Nix-land.  Beware the angle-brackets, as they say.

I'm closing this issue for now.  Feel free to reopen or open another issue if I missed something.
